Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,10 +54,20 @@ jobs:
       id: mlflow-run
       working-directory: ./MLProject
       run: |
+        # Tambahkan debug output
+        echo "Available runs:"
+        mlflow runs list --experiment-name "random_forest_experiment_with_tuning" -o json
+        
         RUN_ID=$(mlflow runs list --experiment-name "random_forest_experiment_with_tuning" \
                 --query "tags.mlflow.runName = 'Tuned_Random_Forest'" -o json | jq -r '.[0].info.run_id')
-        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
-        echo "Retrieved Run ID: $RUN_ID"
+        
+        if [ -z "$RUN_ID" ]; then
+          echo "Error: Failed to get Run ID"
+          exit 1
+        else
+          echo "Retrieved Run ID: $RUN_ID"
+          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
+        fi
         
     - name: 7. Docker Hub Login
       uses: docker/login-action@v3
