Update workflow.yml
cek docker

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -47,9 +47,10 @@ jobs:
       id: get-run-id
       working-directory: ./MLProject
       run: |
-        RUN_ID=$(mlflow runs list --experiment-name "rf_experiment_tuning" --query "tags.mlflow.runName = 'RF_Tuned_Run'" -o json | jq -r '.[0].info.run_id')
+        echo "Getting latest MLflow run ID from experiment"
+        RUN_ID=$(mlflow runs list -e rf_experiment_tuning -o json | jq -r '.[0].info.run_id')
         echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
-        echo "Found Run ID: $RUN_ID"
+        echo "Found Run ID: $RUN_ID""
         
     - name: 7. Login to Docker Hub
       uses: docker/login-action@v3
@@ -61,11 +62,14 @@ jobs:
       if: steps.get-run-id.outputs.run_id != ''
       run: |
         IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/smsml-model:latest"
+        echo "🛠 Building Docker image from model run..."
         mlflow models build-docker \
           --model-uri "runs:/${{ steps.get-run-id.outputs.run_id }}/rf_best_model" \
-          --name "$IMAGE_NAME"
-        docker push "$IMAGE_NAME"
-        echo "Docker image pushed: $IMAGE_NAME"
+          --name "$IMAGE_NAME" || { echo "❌ Failed to build Docker image"; exit 1; }
+
+        echo "🚀 Pushing Docker image to Docker Hub..."
+        docker push "$IMAGE_NAME" || { echo "❌ Failed to push image to Docker Hub"; exit 1; }
+        echo "✅ Docker image pushed: $IMAGE_NAME"
         
     - name: 9. Upload Artifacts
       uses: actions/upload-artifact@v4
